version: "3.0"

services:
    app:
        build:
          context: .
          dockerfile: Dockerfile.local
        volumes:
          - /app/node_modules
          - ./src:/app
        ports:
          - 3000:3000