apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.microservice.name }}-deployment"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
  template:
    metadata:
      name: {{ .Values.microservice.name }}
      labels: # labels to select/identify the deployment
        app: {{ .Values.microservice.name }}  
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:     # pod spec                  
      containers:
      - name: {{ .Values.microservice.name }}
        {{- if .Values.image.tag }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: nodejsport
          containerPort: {{ .Values.service.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: PORT
            value : "{{ .Values.service.port }}"
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
