apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.microservice.name }}-svc"
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.microservice.name }}